### ISSUE TITLE
Option[Int] field is silently set to Option[Double] if the BSON contains a double

### ISSUE THREAD

**Issue by ghost** [salat/salat#148]
Consider the following Scala class and BSON value:

    case class Foo(bar: Option[Int])
    
    { "bar": 2.0 }

I would expect that if I tried to deserialize this, it would either 1. refuse to deserialize it and give me an error since it's not the right numeric type, or 2. coerce the Double value to an Int.

Instead, it appears to succeed, and returns a Foo instance. But it's an invalid instance— because the `bar` property has actually been set to an `Option[Double]` (`Some(2.0)`)! Due to type erasure, the case class constructor allows this to happen; I only see the error when I try to _use_ the property value, and it attempts to unbox an Int only to find that it's really a Double.

**Comment by noahlz** [comment]
What is the specific error / stacktrace you get (if any) when you call `foo.bar`?

**Comment by diagonal-e** [comment]
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
        at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:105)

Note that that doesn't happen if I just call `foo.bar`— the property accessor will still work, since from the point of view of the runtime an `Option` is just an `Option`. I get the error if I try to do `foo.bar.map(f)` where `f` is something that takes an `Int` parameter (and tries to do arithmetic with it, for instance, so it'll get unboxed, rather than just treating it as an object).

**Comment by noahlz** [comment]
```scala
case class MaybeIntHolder(_id: ObjectId = new ObjectId, i: Option[Int])
object MaybeIntHolderDAO extends SalatDAO[MaybeIntHolder, ObjectId](collection = MongoConnection()("test")("maybeInts"))

    val maybeInt = MaybeIntHolder(i = Option(1))
    MaybeIntHolderDAO.save(maybeInt)
    println("Saved: " + maybeInt)
    val found = MaybeIntHolderDAO.findOneById(maybeInt._id)
    println("Found: " + found)
```
prints something like:

```
Saved: MaybeIntHolder(5589bef9e4b0e3db1d673d33,Some(1))
Found: Some(MaybeIntHolder(5589bef9e4b0e3db1d673d33,Some(1)))
```
Meanwhile in mongo:

```javascript
NOVUSNYCLK162(mongod-2.4.13) test> db.maybeInts.find()
{
  "_id": ObjectId("5589be94e4b0b02f0de46a05"),
  "_typeHint": "com.novus.salat.examples.MaybeIntHolder",
  "i": 1
}
```

If you were to manually insert the data into mongo with a double value, outside of your salat code, it would not work.  This is just like in a traditional ORM - if you insert invalid data into a field and then de-serialize it, it will blow up.

**Comment by diagonal-e** [comment]
Right, by definition this is a situation where there is invalid data in Mongo. And as I said, "blowing up" is a behavior I would consider correct— as long as it blows up _in the deserialization call_. It should not be telling me that it deserialized it OK, but returning a case class instance that contains a type that's not even legal for that case class to contain.

In other words, we can't stop someone with Mongo access from hacking something bad into Mongo, because Mongo is not type-safe. But once I have a _Scala_ object that claims to be of some type, I should be able to rely on it really being of that type.

**Comment by diagonal-e** [comment]
Again, the only reason this can happen at all is because of type erasure-- i.e. Scala is not really as type-safe as it seems to be, when it comes to parameterized types. But normally the compiler stops us from screwing up something like this; you have to go to a bit of trouble to create a poisonous property like that, e.g. casting it to `Option[Any]` and then using reflection to invoke the case class constructor. Any library that needs to use such unsafe techniques should be using them carefully. Creating and returning an object that the language is not even supposed to allow you to create is definitely not "just like a traditional ORM."

**Comment by rktoomey** [comment]
I'm sorry Salat does not coerce your doubles to ints but you're being ad hominem.

I understand you're frustrated that your specific case doesn't work perfectly, but allowing _automatic_ narrowing primitive conversion could cause loss of information about your numeric values.  The converse case, which is a widening conversion, actually does work - try putting an integer wrapped in `NumberInt` into MongoDB or JSON and it will be widened to a double as expected.  Even in an `Option`.

By default, the mongo shell treats all numbers as floats - so using `Int` in Scala would require the process inserting into MongoDB to properly wrap the inserted data in `NumberInt`.  Can't guarantee that?  Use a Double and narrow to Int yourself, choosing whatever loss of precision is acceptable to your app.

**Comment by diagonal-e** [comment]
@rktoomey, I don't understand your first sentence at all. What on earth did I say that was "ad hominem", or directed at any person at all? All I can see that you might have been responding to was when I used the word "carefully"; if that was it, I didn't mean that the authors of the code were being careless, I meant that the use of reflection carries some well-known risks that can be avoided through a bit of extra checking that isn't currently being done.

Anyway, I never said I expected my specific case to _work_. I did mention "coerce the double to an int" as _one_ possible approach it could take, but I also said that it would be completely appropriate for it to fail— in fact I think most of us would prefer it to fail, rather than letting the bad data stay in Mongo without us noticing it! But it should fail _in deserialization_. I don't know how to put this any more clearly. I think it's generally inappropriate for any Scala method to construct and return a Scala object that appears valid but will cause a runtime error if you simply use one of its properties. And the contract for a deserializer is "If I return an error, then the input data was bad; but I return an object, then the object is well-formed."

The other reason that the specific point of failure matters is more practical than philosophical. With the current behavior, it is very easy for the `bar` property of the returned object to be passed through many different levels of code and different objects before it gets to something that tries to use the value; and at that point, your stacktrace may not provide much of a clue as to where the poison value originally came from. Whereas if it blows up in Salat, it's obvious that the problem is in the database.

This really goes back to the reasons we use strongly-typed languages in the first place, so that we can have some degree of certainty that no matter how many mistakes we may have made elsewhere, at least when we get to this piece of code that takes a parameter of type A, we know it really is an A.

**Comment by rktoomey** [comment]
Salat could blow up if narrowing is required.  We would welcome your pull
request.

**Comment by diagonal-e** [comment]
I'm not sure we are talking about the same thing. I'm not asking for narrowing or coercion; please forget that I ever mentioned coercing doubles to ints even as a vague possibility. All I really want is for it not to pass a value into my case class constructor that, if it weren't for type erasure, would not be possible to store in that case class at all. Salat already has the necessary type information (otherwise it would not know the right way to _serialize_ `Option[Int]`), and it's smart enough not to set a String property to an Int value, for instance. So I was hoping that this might not be a big hassle to implement, but since I'm not familiar with the code yet, I could certainly be wrong.

(Also, I'd still love to know what you meant by "ad hominem", not in order to argue about that but just to understand, since it definitely was not my intention to insult anyone in any way.)

**Comment by noahlz** [comment]
@diagonal-e I certainly agree that we could detect issues like this "earlier" by comparing the database value with the field specification. This is something I will look into.

However, the end result will be the same - an exception thrown, correct? The database value will not be usable, and there's not a clear way to "salvage" it - garbage in, garbage out.

Is your goal to have a slightly more actionable exception than `ClassCastException`? Can you provide a sketch of how you want the exception to look and/or how your code would recover from it?

**Comment by diagonal-e** [comment]
@noahlz, my goal would be to have the exception be thrown from the deserialization method— just as it would be for any other kind of malformed data, e.g. if a required property in the case class was not present in the BSON, or if an Int property in the case class had a String value in the BSON. There is already, always, the possibility that some database content cannot be successfully deserialized, and there's usually no way to meaningfully recover from that condition, but that would be up to the application.

The problem with the current behavior isn't so much that it is a `ClassCastException` as opposed to some other kind of exception; it's that it occurs in a subtle way that may be very far removed from the cause. Once there is a bad `Option` value in the returned case class, it's like a little booby-trapped gift box that only blows up when you open it, which could be quite a while later when it's no longer clear where the box originally came from. Again, I think it's fair to say that the contract for any kind of deserializer is that _if_ it returns an instance of the requested type instead of an error, then that means that the instance is well-formed by the standards of the language (e.g. you can't guarantee that an Int property contains a positive number, or that a String is non-empty, but you can guarantee that it _is_ an Int or a String).

**Comment by noahlz** [comment]
@diagonal-e Booby-trapped object - yes, I hate those too.

**Comment by noahlz** [comment]
Ok, it took me a little over a year to get back to this (sorry everybody), but I reproduced this over in my salat-examples project:

https://github.com/noahlz/salat-examples/commit/4a48387d2fa0498c3241b9d7263d09b28792dc8e

This could still be the basis of a unit test, although my recommendation remains: don't do this!

The fix is most likely going to be, as the (now gone) reporter suggested: throw a more specific error earlier at deserialization time.

**Comment by noahlz** [comment]
To make this fail "fast" at deserialization time, something is probably needed at `Injectors.scala` line 84 - that's where we should be checking for a the incoming value to match the value of the target Option. We do it for several other data types, but not all possible cases (if that is in fact possible).

**Comment by noahlz** [comment]
So I looked into this further.

It turns out that Salat does narrowing coversions by default when you have a `Map[_, Int]`. I tested this out and it very plainly takes a double that was stuffed into the value of a `[Map, Int]` entry and narrows it with `intValue()`

See noahlz/salat-examples@35c588b8c

**Comment by noahlz** [comment]
Just learned that even a field with type `Int` will be narrowed silently.

noahlz/salat-examples@da2a68941aa1a935b

**Comment by noahlz** [comment]
How far do we want to take this?

```
scala> List(1, 1.0, 1.01, 1.0000001, 1.0000000000001).map(_ == 1)
res8: List[Boolean] = List(true, true, false, false, false)
```

If you are a types zealot, only the first element in that list should be true. `1 == 1.0` should be `false` because types.

I think a reasonable solution here is to check that the values are equal after conversion, and hope for the best in terms of double estimation on CPU architectures. :sweat:

**Comment by noahlz** [comment]
"If I put Double values into an Int field, shouldn't the machine produce the correct value?"

I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question.

**Comment by noahlz** [comment]
PR opened for this #178
