### ISSUE TITLE
Update Casbah to 2.8.2 in Salat 1.10.x to support connecting to Mongo 3.x server.

### ISSUE THREAD

**Issue by angeloh** [salat/salat#158]
I am using https://github.com/novus/salat. But it seems that salat is using Casbah 2.7. Our mongo server is 3.0.6. But we are not able to connect and always got this error.

    Configuration error: Configuration error[Access denied to MongoDB database: [mg_prod] with user: [mydbuser]]
            at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
            at play.api.Configuration.reportError(Configuration.scala:743)
            at se.radley.plugin.salat.SalatPlugin$MongoSource.connection(SalatPlugin.scala:36)
            at se.radley.plugin.salat.SalatPlugin$$anonfun$onStart$1.apply(SalatPlugin.scala:136)
            at se.radley.plugin.salat.SalatPlugin$$anonfun$onStart$1.apply(SalatPlugin.scala:131)

Can you please give me some idea how should I fix this issue?

**Comment by noahlz** [comment]
Hello, as it turns out, there is a just-opened PR to fix this #157.  Perhaps pull and test that branch to see if it solves your issue (if not - your chance to contribute!)

**Comment by danslapman** [comment]
@angeloh, as a workaround You can just add an explicit Casbah 2.8.2 dependency to Your project, it will work in most cases.

**Comment by mupakoz** [comment]
I can confirm that method proposed by @danslapman works.

**Comment by noahlz** [comment]
Hello - I have just published `1.10.0-SNAPSHOT` which among other things incorporates @danslapman's  PR.

I know it's been a long while since issue was opened, but if someone wants to give the snapshot release a while and confirm it's all good, it will give me some confidence to do a stable release of `1.10.0` with Casbah 2.8.2 support.

Notes:
- The snapshot is only available from the Sonatype OSS repo, so you may have to add that to your project definition
- In 1.10.0 we're changing the package name from `com.novus.salat_` to just `salat._` (not yet though)

**Comment by sief** [comment]
I can only find a Scala 2.10 version in the Sonatype repo. If you publish a 2.11 version I could run my tests against it, if this is of any help...

**Comment by noahlz** [comment]
Ah, oops. I did `sbt +publish` which only publishes the cross build.

Re-published, try now!

**Comment by sief** [comment]
Smoke test of my Play2 app was fine. The specs2 tests worked, too, with one exception: when I insert a duplicate for a unique index I get a `SalatInsertError` instead of `DuplicateKeyException`. Is this intended? How can I detect a `DuplicateKeyException`?

**Comment by noahlz** [comment]
Looks like that is a result of this commit:

cd5a43c43

**Comment by noahlz** [comment]
I suspect that a PR is in order to expose the DuplicateKeyException, possibly as a root cause exception.

**Comment by sief** [comment]
ok, I'll have a look at it over the weekend. It's good that the call to `getCachedLastError` has been removed, but do you think it's really necessary to convert the driver exceptions into Salat errors? (the `WriteResult` will be always `null`, anyway)

**Comment by noahlz** [comment]
If we change the behavior to just throw the original driver exception, we just have to be sure to document that change in release notes.

I only see value in wrapping an exception if it adds some kind of meta-information relevant to Salat. If `SalatException` doesn't do that, then we should just let the driver error bubble up.

**Comment by sief** [comment]
This Exception conversion was introduced with the commit you mentioned above. So if we remove it, the only change to document here is the removal of `getCachedLastError` and the corresponding Salat errors. In the previous versions the actual driver exceptions just bubbled up, afaik. (That's why my tests failed)

**Comment by noahlz** [comment]
Casbah 2.8.2 / Mongo 3.x support is available for testing in the lastest `1.10.0-SNAPSHOT` which is now published in the Sonatype OSS snapshot repo.

Feedback appreciated!

**Comment by sief** [comment]
smoke test of my app and specs2 query tests all OK. 👍 
Tested with Scala 2.11.8 and MongoDB 3.0.12

**Comment by noahlz** [comment]
I have published Salat v1.10.0 which has support for Casbah 2.8.2 and Mongo 3.0

**Comment by sief** [comment]
@noahlz awesome, this is great news, many thanks for your efforts 👍
